name: 'fiosiovet'
version: '1.0.0'
profile: 'bigquery'
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
models:
  native:
    +schema: 'native'
    transient: false
  analytics:
    +schema: 'analytics'
    transient: false