bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /opt/airflow/credential/gerolingcp-9ff636503d6b.json
      project: gerolingcp
      dataset: WeatherAPI
      threads: 1 